@startuml
hide footbox

participant AdmincredentialIssuer
activate AdmincredentialIssuer


AdmincredentialIssuer-> AdmincredentialIssuer: AdminIssueCredential()
activate AdmincredentialIssuer

AdmincredentialIssuer-> AdmincredentialIssuer: MatchUserID()
activate AdmincredentialIssuer
return matchStatus

alt matchStatus is true

AdmincredentialIssuer-> AdmincredentialIssuer: sendIssueReq()
activate AdmincredentialIssuer
note right: sends request as schema to ledger

AdmincredentialIssuer-> HttpClient:PostAsync()
activate HttpClient
return response

alt requests successful



AdmincredentialIssuer-> AdmincredentialIssuer: GetCredDef()
activate AdmincredentialIssuer
AdmincredentialIssuer-> HttpClient:GetAsync()
activate HttpClient
return response

loop all transactions in response
note right: find matching schema to endorse
alt if match
AdmincredentialIssuer-> AdmincredentialIssuer: GenerateKey()
activate AdmincredentialIssuer
note right: calculates credential key
AdmincredentialIssuer-> AdmincredentialIssuer: GetAESKey()
activate AdmincredentialIssuer
return AESKey
AdmincredentialIssuer-> AdmincredentialIssuer: SQLAddKey()
activate AdmincredentialIssuer
return
note right: adds credential key to server
return
end

end
return
end

end
return
return
@enduml