@startuml 
hide footbox

participant DHMessager_Inviter_A
participant Ledger
participant DHMessager_Invitee_B


activate Ledger


activate DHMessager_Inviter_A
DHMessager_Inviter_A-> DHMessager_Inviter_A: AShareParams()
activate DHMessager_Inviter_A
note left: function run when "invite" button pressed
DHMessager_Inviter_A-> DHMessager_Inviter_A: Generate DHParameters
DHMessager_Inviter_A-> Ledger: PostDHParameters()
Ledger --> DHMessager_Inviter_A
DHMessager_Inviter_A-> DHMessager_Inviter_A: GenerateKeyPair()
DHMessager_Inviter_A-> Ledger: PostStaticPublicKey()
Ledger --> DHMessager_Inviter_A
DHMessager_Inviter_A-> DHMessager_Inviter_A: AddDHPrivateKeySQL()
return




activate DHMessager_Invitee_B
DHMessager_Invitee_B-> DHMessager_Invitee_B: BGetParamsAndCalcSecret()
activate DHMessager_Invitee_B
note right: function run when "accept" button pressed
DHMessager_Invitee_B-> Ledger: GetDHParams()
Ledger -> DHMessager_Invitee_B: foundDHParamms
DHMessager_Invitee_B-> DHMessager_Invitee_B: DHKeyGenerationParameters(foundDHParams)
DHMessager_Invitee_B-> Ledger: GetStaticKeyString()
Ledger -> DHMessager_Invitee_B: StaticKeyString
DHMessager_Invitee_B-> DHMessager_Invitee_B:DHPublicKeyParameters()
DHMessager_Invitee_B-> Ledger:PostStaticPublicKey()
Ledger --> DHMessager_Invitee_B
DHMessager_Invitee_B-> DHMessager_Invitee_B: CalculateAgreement
note right: calculate the symmetric key
DHMessager_Invitee_B-> DHMessager_Invitee_B: AddAESKeyToWallet
return
deactivate DHMessager_Invitee_B


DHMessager_Inviter_A-> DHMessager_Inviter_A: ACalculateSecret()
activate DHMessager_Inviter_A
note left: function run when "establish" button pressed
DHMessager_Inviter_A-> Ledger: GetDHParams()
Ledger -> DHMessager_Inviter_A: foundDHParamms
DHMessager_Inviter_A-> Ledger: GetStaticKeyString()
Ledger -> DHMessager_Inviter_A: StaticKeyString
DHMessager_Inviter_A-> DHMessager_Inviter_A: GetDHPrivateKeySQL()
DHMessager_Inviter_A-> DHMessager_Inviter_A: CalculateAgreement
note left: calculate the symmetric key
DHMessager_Inviter_A-> DHMessager_Inviter_A: AddAESKeyToWallet
return
deactivate DHMessager_Inviter_A






@enduml