@startuml
hide footbox
-> CredentialIssuer: GetKeys()
participant CredentialIssuer
activate CredentialIssuer


CredentialIssuer -> CredentialIssuer: GetCredDef()
activate CredentialIssuer

participant HttpResponseMessage

CredentialIssuer -> HttpResponseMessage:
activate HttpResponseMessage
HttpResponseMessage -> CredentialIssuer:response

alt response is successful
deactivate HttpResponseMessage

loop all transactions in reponse
alt if match

CredentialIssuer -> CredentialIssuer: GenerateKey()
activate CredentialIssuer
CredentialIssuer -> CredentialIssuer: GetAESKey()
activate CredentialIssuer
CredentialIssuer -> CredentialIssuer: SQLAddKey()
activate CredentialIssuer
return
return
return 

end
end
end
return
return
@enduml