@startuml
hide footbox

participant CredentialIssuer
activate CredentialIssuer


CredentialIssuer -> CredentialIssuer: RequestCredential()
activate CredentialIssuer

CredentialIssuer -> CredentialIssuer: CheckAdminConnection()
activate CredentialIssuer
return conenctionStatus
CredentialIssuer -> AdminCredentialIssuer: MatchUserID()
activate AdminCredentialIssuer
return matchStatus
alt connectionStatus and matchStatus is true


CredentialIssuer -> CredentialIssuer: sendReq()
activate CredentialIssuer
note right: sends request as schema to ledger

CredentialIssuer -> HttpClient:PostAsync()
activate HttpClient
return response


return



end
return
return
@enduml